# Dockerfile used for dev environment

FROM node:24-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies including devDependencies
RUN npm install

# Expose server port
EXPOSE 8080

# Start server in watch mode
CMD ["npm","run","dev"]
