CREATE TABLE IF NOT EXISTS announcement (
    id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    message TEXT NOT NULL,
    author VARCHAR(255) NOT NULL,
    created_at BIGINT NOT NULL DEFAULT (UNIX_TIMESTAMP(NOW(3)) * 1000)
) ENGINE=InnoDB;